### PR TITLE
chore: Migrating to AndroidX

### PR DESCRIPTION
**Pull request by MohamedWael**

### CODE REVIEW

**Comment by pilgr** [comment]
Hi @MohamedWael ! Thanks for the PR! 

When running ` ./gradlew clean testDebug` I got many compilation errors like 
```
> Task :paperdb:compileDebugUnitTestKotlin FAILED
e: ./paperdb/paperdb/src/androidTest/kotlin/io/paperdb/KotlinCompatibilityTest.kt: (3, 17): Unresolved reference: test
...
```
Could you check out if it compiles on your side? Thanks.

**Comment by MohamedWael** [comment]
I've fixed it, it was a missing dependency

**Comment by MohamedWael** [comment]
Hello @pilgr,
Any updates?

**Comment by pilgr** [comment]
@MohamedWael sorry for the late response, I'm on it

**Comment by pilgr** [comment]
Works great, thanks for the PR!

**Pull request merged**
