### PR TITLE
Remove protocol buffers dependency

### PR DESCRIPTION
**Pull request by pakoito**
As stated in https://github.com/magro/kryo-serializers/issues/59, kryo-serializer adds several dependencies that aren't used by PaperDb. One of them is protocol buffers, which is 6k lines heavy: http://www.methodscount.com/?lib=io.paperdb%3Apaperdb%3A1.5

This PR creates a local copy of the serializers tagged with the commit they were taken from, to be used until (if) kryo-serializers is updated to not include heavy dependencies. Joda-time is kept only as a test dependency.

This PR also updates the build scripts, plugins, and gradle to the latest version.

### CODE REVIEW

**Comment by pakoito** [comment]
kryo-serializers has fixed the dependency https://github.com/magro/kryo-serializers/pull/60 and released a new version https://github.com/magro/kryo-serializers/releases/tag/kryo-serializers-0.40

This PR is not relevant anymore. I'll do the update one now.

**Comment by pilgr** [comment]
Thanks! Also please make PR for `development` branch.

**Comment by pakoito** [comment]
Done! Merge the one you want!

**Comment by pakoito** [comment]
This should be the right one: https://github.com/pilgr/Paper/pull/57

**Pull request closed without merging**
